### ISSUE TITLE
[FR] 为无痕模式/未登录添加本地观看记录

### ISSUE THREAD

**Issue by VillagerTom** [orz12/pilipala#10]
### 功能描述
习惯了无痕模式后感觉有点不习惯，刷了刷官方B站想起来未登录模式下也有历史记录。如果无痕模式能像官方B站那样本地记录历史观看就好了。

### 目标
本地记录无痕模式播放视频的历史记录、进度等，使无痕模式更加方便实用。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by orz12** [comment]
不会支持，违背了无痕的本意，也会造成混淆。而且目前也没有本地保存历史记录的机制

**Comment by VillagerTom** [comment]
可以单独做一个列表显示嘛。而且可以做个隐蔽触发手势，比如长按“我的”页眼睛图标5秒。

**Comment by VillagerTom** [comment]
我使用无痕模式的目的是欺骗B站推荐机制，对于想让B站知道我看的，我会关闭无痕模式让B站记录一下。
