### ISSUE TITLE
[BUG] 登录界面白屏

### ISSUE THREAD

**Issue by 2013ZRZ** [orz12/pilipala#104]
### 问题描述
登录账号时网页出现白屏。

### 复现步骤
1. 首页点击右上角头像；
2. 点击头像进入登录页面；
3. 出现白屏情况，点击顶部任何按钮都没有反应，点击「刷新登录态」会提示「账号未登录」。

### 预期行为
进入正常登录页面，进行登录账号。

### 错误日志
这个行为没有留下错误日志。以下是一些有可能有用的信息：
* Android 版本：7.1.2
* soc：rk3288
* 设备型号：FID3288-F8
* PiliPalaX 版本：1.0.20+150（[下载地址](https://pilipalanet.mysxl.cn/pilipala-x)）

### 相关信息
![Screenshot_20240615-130829](https://github.com/orz12/pilipala/assets/130883435/4b560a28-8b4d-49bf-8bab-22b4d0b6fb14)

**Comment by orz12** [comment]
这个是系统webview的问题，你最近有更新过吗

**Comment by 2013ZRZ** [comment]
已解决，感谢🙏🏻

> 这个是系统webview的问题，你最近有更新过吗，或者太旧了

的确，但不是版本的问题，而是设置的问题，我是类原生，在设置>关于手机/平板电脑>高级设置>应用>WebView实现>调整为Google WebView，重启就能用了


可否把我的方法放进常见问题解答里面，能帮到更多用户，同时为开发者省些麻烦（大概）
