### ISSUE TITLE
[bug]播放视频时突然灰屏，声音还在

### ISSUE THREAD

**Issue by Maolaohei** [orz12/pilipala#113]
### 问题描述
播放视频会突然灰屏，但是声音还是正常播放。
使用返回键能返回主页。

### 复现步骤
随便播放视频都有概率发生。
发生频率：偶发性

### 预期行为
正常播放

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。
日志时间范围[10分钟内]，第一条是最新的log，后面是之前的log。按错误日志时间排序

[log.txt](https://github.com/user-attachments/files/16012855/log.txt)

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
视频：BV1gi421v7hK
![Screenshot_2024-06-26-02-30-19-652_com.miui.home-edit.jpg](https://github.com/orz12/pilipala/assets/24179463/e1c1e868-fc28-4f4f-b0af-eafa655b2fb8)

**Comment by Maolaohei** [comment]
又触发了一次
PiliPalaX错误日志
********************
------- 设备信息 -------
id: UKQ1.230804.001
board: taro
bootloader: unknown
brand: Redmi
device: mondrian
display: UKQ1.230804.001 release-keys
fingerprint: Redmi/mondrian/mondrian:14/UKQ1.230804.001/V816.0.24.6.17.DEV:user/release-keys
hardware: qcom
host: pangu-build-component-system-300374-kkwpp-fk31z-0lgxk
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23013RK75C
product: mondrian
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V816.0.24.6.17.DEV
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-06-01
------- 应用信息 -------
environment: release
version: 1.0.21-beta.2
appName: PiliPalaX
buildNumber: 1600
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
RangeError (length): Invalid value: Valid value range is empty: 3
------- 错误堆栈 -------
#0      IdUtils.bv2av (package:PiliPalaX/utils/id_utils.dart)
#1      VideoDetailController.onInit (package:PiliPalaX/pages/video/detail/controller.dart:152)
#2      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66)
#3      InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12)
#4      GetInstance._startController (package:get/get_instance/src/get_instance.dart:254)
#5      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:205)
#6      GetInstance.find (package:get/get_instance/src/get_instance.dart:302)
#7      GetInstance.put (package:get/get_instance/src/get_instance.dart:87)
#8      Inst.put (package:get/get_instance/src/extension_instance.dart:89)
#9      _VideoDetailPageState.initState (package:PiliPalaX/pages/video/detail/view.dart:79)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#163    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#179    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#180    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#182    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#190    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#202    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#218    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#232    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#234    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024)
#235    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#240    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#244    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#248    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#249    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#252    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#253    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#254    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#258    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#259    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#262    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#264    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#269    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#271    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#273    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#274    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#276    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#277    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#278    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#280    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#281    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#282    Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#283    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#284    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#285    Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#286    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#287    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#288    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#289    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#290    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#291    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#292    _invoke (dart:ui/hooks.dart:312)
#293    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#294    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by xsfx0313** [comment]
6，你这个错误日志把所有的issue都提及了一遍，在哪都能看见，您能把他放进 code 里吗？即在前后加上\```三个单引号
```
    ```
    你的错误日志
    ```
```
在你发出的那一条issue的右上角有三个点，再点一下edit就可以修改了。谢谢！

**Comment by Maolaohei** [comment]
> 6，你这个错误日志把所有的issue都提及了一遍，在哪都能看见，您能把他放进 code 里吗？即在前后加上\```三个单引号
> ```
>     ```
>     你的错误日志
>     ```
> ```
> 在你发出的那一条issue的右上角有三个点，再点一下edit就可以修改了。谢谢！维护环境，人人有责
> 

收到

**Comment by xsfx0313** [comment]
> > 6，你这个错误日志把所有的issue都提及了一遍，在哪都能看见，您能把他放进 code 里吗？即在前后加上\```三个单引号
> > ```
> >     ```
> >     你的错误日志
> >     ```
> > ```
> > 在你发出的那一条issue的右上角有三个点，再点一下edit就可以修改了。谢谢！维护环境，人人有责
> > 
> 已删除所有内容。不过别人的问题里引用还是有

感谢！
