### ISSUE TITLE
评论区显示白屏

### ISSUE THREAD

**Issue by Gesui0429** [orz12/pilipala#12]
### 问题描述
请提供一个清晰而简明的问题描述。
在视频中切换最热/最新后评论无法正常加载
### 复现步骤
请提供复现该问题所需的具体步骤。
在视频评论最新中拉到底，再切换为最热后无法加载
### 预期行为
请描述你期望的正确行为或结果。
评论正常加载
### 错误日志
请提供关于-错误日志中的内容。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。
PiliPalaX错误日志 
 ********************
日志1:------- 设备信息 -------
id: RP1A.200720.011
board: chopin
bootloader: unknown
brand: Redmi
device: chopin
display: RP1A.200720.011
fingerprint: Redmi/chopin/chopin:11/RP1A.200720.011/V12.5.1.0.RKPCNXM:user/release-keys
hardware: mt6891
host: c5-xm-ota-bd022.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2104K10AC
product: chopin
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V12.5.1.0.RKPCNXM
versionPreviewSdk: 0
versionRelease: 11
versionSdk: 30
versionSecurityPatch: 2021-04-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1243
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------
2:PiliPalaX错误日志 
 ********************
------- 设备信息 -------
id: RP1A.200720.011
board: chopin
bootloader: unknown
brand: Redmi
device: chopin
display: RP1A.200720.011
fingerprint: Redmi/chopin/chopin:11/RP1A.200720.011/V12.5.1.0.RKPCNXM:user/release-keys
hardware: mt6891
host: c5-xm-ota-bd022.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2104K10AC
product: chopin
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V12.5.1.0.RKPCNXM
versionPreviewSdk: 0
versionRelease: 11
versionSdk: 30
versionSecurityPatch: 2021-04-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1243
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
type 'String' is not a subtype of type 'List<dynamic>'
------- 错误堆栈 -------
#0      SSearchController.onLongSelect (package:PiliPalaX/pages/search/controller.dart:118)
#1      _SearchPageState._history.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:PiliPalaX/pages/search/view.dart:260)
#2      SearchText.build.<anonymous closure> (package:PiliPalaX/pages/search/widgets/search_text.dart:28)
#3      _InkResponseState.handleLongPress (package:flutter/src/material/ink_well.dart:1208)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#5      LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:706)
#6      LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:607)
#7      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:658)
#8      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:601)
#9      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
------- CUSTOM INFO -------
### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/e78cd8b179352ac6b969c9fc2b22186e199741dd
