### ISSUE TITLE
Request:投稿相关功能

### ISSUE THREAD

**Issue by n0name-o0o0** [orz12/pilipala#13]
### 功能描述

上传、_管理、分P（非必需）_视频
官方版太臃肿了又是AI剪辑又是智能成片的...

### 实现方式

类似原版客户端的那种？或者提供一个快捷网页入口？

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/03b46bf6dfe332d318f0f2058f8f9f6e97779d52
由于涉及读权限的问题，该功能（尤其是上传）建议在浏览器打开使用，直接点击可能没有反应。
