### ISSUE TITLE
通知已读后红点不会自动消失需要手动刷新

### ISSUE THREAD

**Issue by DrinkingHook** [orz12/pilipala#15]
### 目标
希望已读后自动刷新消失红点https://github.com/orz12/pilipala/assets/113015731/8f260671-7818-4752-9bb7-480b035636d8

**Comment by orz12** [comment]
私信的开发内容比较多，目前还只是初步做了一下，将优先解决可用性问题。红点等问题会在后续完善。

**Comment by orz12** [comment]
做完了 稍后更新
