### ISSUE TITLE
视频简介页丢失 1.0.19+131

### ISSUE THREAD

**Issue by kuektic** [orz12/pilipala#17]
### 问题描述
打开任意一个视频，向左滑进入评论区，点击任意一个用户的头像进入其主页，然后再返回视频评论区，向右滑回到视频简介页，会发现简介页内容缺失

### 复现步骤
请见问题描述

### 预期行为
修复这个bug

### 错误日志

============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-02-24 14:53:07.436253

------- DEVICE INFO -------
id: TP1A.220624.014
board: pearl
bootloader: unknown
brand: Redmi
device: pearl
display: TP1A.220624.014
fingerprint: Redmi/pearl/pearl:13/TP1A.220624.014/V14.0.10.0.TLHCNXM:user/release-keys
hardware: mt6895
host: pangu-build-component-system-521136-3l0xh-pxxtm-3kh9j
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23054RA19C
product: pearl
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.10.0.TLHCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-10-01

------- APP INFO -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1313
packageName: com.orz12.PiliPalaX

---------- ERROR ----------
Null check operator used on a null value

------- STACK TRACE -------
#0      new VideoIntroController (package:PiliPalaX/pages/video/detail/introduction/controller.dart:26)
#1      _VideoIntroPanelState.initState (package:PiliPalaX/pages/video/detail/introduction/view.dart:52)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#5      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:225)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#48     SingleChildRenderO

app版本号1.0.19+131、系统版本安卓13、设备型号红米note12T Pro等

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
![Screenshot_2024-02-24-14-47-41-802_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/95989221/6afba2dd-4291-495a-93ee-579d0d673295)
![Screenshot_2024-02-24-14-47-32-894_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/95989221/83e55999-4448-4dfc-877d-5e61ee1bfb16)
![Screenshot_2024-02-24-14-47-25-779_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/95989221/e3fbbbef-535f-42dc-a76b-dc2f174b31b3)

**Comment by zackzheng1121** [comment]
確實

**Comment by orz12** [comment]
明天修

**Comment by orz12** [comment]
修好了
