### ISSUE TITLE
点一个视频，再点下面推荐的视频，或者点正在播放视频的UP主主页，再点返回会黑屏闪屏

### ISSUE THREAD

**Issue by PlusLogic** [orz12/pilipala#19]
### 问题描述
点一个视频，再点下面推荐的视频，或者点正在播放视频的UP主主页，再点返回会黑屏再闪一下

### 复现步骤
点一个视频，再点下面推荐的视频，或者点正在播放视频的UP主主页，再点返回

### 预期行为
正常返回，无黑屏闪屏

### 错误日志

PiliPalaX错误日志 
 ********************
------- 设备信息 -------
id: QKQ1.190828.002
board: sdm845
bootloader: unknown
brand: Xiaomi
device: dipper
display: QKQ1.190828.002 test-keys
fingerprint: Xiaomi/dipper/dipper:10/QKQ1.190828.002/V12.5.2.0.QEACNXM:user/release-keys
hardware: qcom
host: c5-miui-ota-bd38.bj
isPhysicalDevice: true
manufacturer: Xiaomi
model: MI 8
product: dipper
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V12.5.2.0.QEACNXM
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-12-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1313
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------

### 相关信息
[]()https://pan.7so.top/s/Q4oCD

**Comment by VillagerTom** [comment]
我问作者了，这是特性(雾，点开下一页会把上一页的组件全部销毁。以后可能会把黑屏替换掉。

**Comment by orz12** [comment]
改成底色了
