### ISSUE TITLE
设置默认拉伸或者填充

### ISSUE THREAD

**Issue by wzgrx** [orz12/pilipala#32]
### 功能描述
默认填充或者拉伸的功能，每次看视频，都得手动打开一次

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
无
![9ef18b735f967f2245c98a2e218f1d42](https://github.com/orz12/pilipala/assets/39661556/325f4315-1a55-45b1-b539-f65f8c6081b1)

**Comment by orz12** [comment]
目前其实是可以保存的 可能你那边的设置有些问题 可以试试卸载重装一下

**Comment by wzgrx** [comment]
> 目前其实是可以保存的 可能你那边的设置有些问题 可以试试卸载重装一下

好的，谢谢开发者大佬
