### ISSUE TITLE
1.0.19+141视频链接不会正常跳转

### ISSUE THREAD

**Issue by IJustWantANamePlease** [orz12/pilipala#44]
### 问题描述
在最新版 (1.0.19+141) 中，通过点击视频链接进入PilipalaX不会打开视频页面。

### 复现步骤
~~首先允许PilipalaX打开B站链接~~
点击任意B站视频的链接

### 预期行为
跳转到PilipalaX后会进入对应视频的页面。

### 错误日志
无

### 版本信息
PilipalaX: 1.0.19+141
系统：PixelOS 14
机型：红米Note 11 TPro

### 相关信息
测试过1.0.19+140是可以正常跳转视频页面的，应该就是141出了问题。
Pilipala之前也有在后台时点链接不会跳转视频的问题，但我指的不是那个，141无论什么情况都无法打开视频页面。

**Comment by orz12** [comment]
可以加tg频道测一下频道内的测试版，如果没问题我就发上来

**Comment by IJustWantANamePlease** [comment]
> 可以加tg频道测一下频道内的测试版，如果没问题我就发上来

更新到+142已经正常了❤️
