### ISSUE TITLE
在平板横屏时将底栏移动至左边

### ISSUE THREAD

**Issue by pigyee** [orz12/pilipala#57]
#53 
### 功能描述
在平板横屏时将底栏移动至左边，即侧栏

### 目标
底栏在横屏时看起来太粗了，关md3看起来难受

##### clash
![Screenshot_20240406_113703_com github kr328 clash](https://github.com/orz12/pilipala/assets/136228019/b18eb966-9404-400f-8524-4848c291812c)
##### dizuku
![Screenshot_20240406_113652_com rosan dhizuku](https://github.com/orz12/pilipala/assets/136228019/28c33743-35c5-411b-9811-bcfa56efd111)
##### c001apk
![Screenshot_20240406_113556_com example c001apk](https://github.com/orz12/pilipala/assets/136228019/6bd32e06-a40d-449f-b61a-2a95df70c66e)

**Comment by orz12** [comment]
已经实现了 在外观中开启 改用侧边栏 即可

**Comment by pigyee** [comment]
草稿
![sketch1719057959664_1](https://github.com/orz12/pilipala/assets/136228019/d6bc28d6-dba7-4b4f-a595-c3f6ad5d764e)
