### ISSUE TITLE
保存图片时错误地提示权限不足

### ISSUE THREAD

**Issue by wanzh5** [orz12/pilipala#64]
### 问题描述
保存图片时提示“相册权限未授权”，但是实际上已经给了所有权限。更新1.0.19+148后才出现。

### 相关信息
![Screenshot_20240414_174244_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/106989902/36bd8484-9ced-4380-b598-cd27aad3af2b)

**Comment by dxuser1919** [comment]
我也是，遇到这种情况

**Comment by xsfx0313** [comment]
同样问题+1，版本同样为+148
无法保存动态图片
