### ISSUE TITLE
[新功能]导出导入配置文件

### ISSUE THREAD

**Issue by xsfx0313** [orz12/pilipala#66]
### 功能描述
可以将系统的配置文件导出和导入

### 解决方案
可以将当前的设置打包为一个json或zip文件，并添加倒入功能

### 其他
如果能在pilipalaX和pilipala之间交换就更好了

ps.提着个issu的原因是想要在我的多台设备之间同步，一次一次手动调太麻烦了，此功能并不着急，如果能采纳就太感谢啦！！

**Comment by orz12** [comment]
已支持

**Comment by orz12** [comment]
但目前是导出到剪贴板（json格式）
