### ISSUE TITLE
所有横屏视频都不能正常全屏，而是保持竖屏的全屏状态

### ISSUE THREAD

**Issue by huajiworld** [orz12/pilipala#7]
### 问题描述
所有横屏视频都不能全屏，已经调过相关设置了，还是不行。
点击全屏按钮时只有一瞬间切换到横屏，再然后就是变成竖屏的全屏状态

### 复现步骤
随便找个横屏视频，点击全屏按钮

### 预期行为
当然是正常全屏了

### 错误日志
没有错误日志。
版本：Release的最新版
系统：Android8.0和Android7.0都有此问题

### 相关信息
https://github.com/orz12/pilipala/assets/65672655/ab88c130-0a0f-42ae-9cb6-2a35d60e603c

**Comment by VillagerTom** [comment]
我这里全屏后随机横屏或竖屏显示。

**Comment by orz12** [comment]
快寄一个低版本安卓手机给我 :P

> 我这里全屏后随机横屏或竖屏显示。 系统屏幕旋转关闭，横屏适配关闭，默认全屏方式为按视频方向。

**Comment by huajiworld** [comment]
> 快寄一个低版本安卓手机给我 :P
> 
> > 我这里全屏后随机横屏或竖屏显示。 系统屏幕旋转关闭，横屏适配关闭，默认全屏方式为按视频方向。

地址在哪，马上寄（

**Comment by orz12** [comment]
我试着推了一个修复commit，不知道是不是这个引起的，只能靠猜测了，可以试一下看看有效果没

**Comment by huajiworld** [comment]
> 我试着推了一个修复commit，不知道是不是这个引起的，只能靠猜测了，可以试一下看看有效果没

没效果捏

**Comment by orz12** [comment]
那我暂时不知道是什么原因，播放页横屏适配是从v96开始引入的，你可以先装之前的版本

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/b4452fd7008b828e7a987d983a48d872d83fa96e
据一位群友反应，v121版本修复了该问题，所以我还是重做了这项改动。我拿了一个安卓9的小米机没法复现这个问题，看来版本可能需要很老才行。

**Comment by huajiworld** [comment]
> https://github.com/orz12/pilipala/commit/b4452fd7008b828e7a987d983a48d872d83fa96e
> 据一位群友反应，v121版本修复了该问题，所以我还是重做了这项改动。我拿了一个安卓9的小米机没法复现这个问题，看来版本可能需要很老才行。

用Android studio 搞个8.0的虚拟机

**Comment by VillagerTom** [comment]
RemixOS我记得好像是Android6

**Comment by orz12** [comment]
虚拟机我电脑带不起来，而且容易崩

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VillagerTom** [comment]
我这台12年前的电脑都跑的起来，看来是硬件特殊😏

**Comment by kaerwwx** [comment]
我也一样
手机:红米k40gaming
系统:android13 miui14.0.5
软件版本:1.0.19+124

**Comment by kaerwwx** [comment]
1.0.19+121也一样

**Comment by huajiworld** [comment]
@orz12 好像有日志了，不懂对不对号
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-02-19 19:09:04.538620

------- DEVICE INFO -------
id: HUAWEIDUB-AL00
board: DUB-AL00
bootloader: unknown
brand: HUAWEI
device: HWDUB-Q
display: DUB-AL00 8.2.0.196(C00)
fingerprint: HUAWEI/DUB-AL00/HWDUB-Q:8.1.0/HUAWEIDUB-AL00/196(C00)R2:user/release-keys
hardware: qcom
host: szvphicpra02071
isPhysicalDevice: true
manufacturer: HUAWEI
model: DUB-AL00
product: DUB-AL00
tags: release-keys
type: user
versionBaseOs: HUAWEI/DUB-AL00/HWDUB-Q:8.1.0/HUAWEIDUB-AL00/195(C00)R2:user/release-keys
versionCodename: REL
versionIncremental: 196(C00)R2
versionPreviewSdk: 0
versionRelease: 8.1.0
versionSdk: 27
versionSecurityPatch: 2020-07-01

------- APP INFO -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1243
packageName: com.orz12.PiliPalaX

---------- ERROR ----------
Bad state: Cannot add event after closing

------- STACK TRACE -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================

**Comment by VillagerTom** [comment]
这个不是，pip小窗的老bug了

**Comment by VillagerTom** [comment]
我用Android7测试也是有问题。与Android5不同的是，7会先横屏一下再变为竖屏，5会直接显示竖屏全屏。

**Comment by VillagerTom** [comment]
噢题主用的是Android7/8，我记得谁用的Android6来着？

**Comment by VillagerTom** [comment]
即使关闭系统屏幕旋转，全屏模式也要读取重力传感器来确定往哪个方向横屏。是不是这里出了问题？

**Comment by huajiworld** [comment]
> 即使关闭系统屏幕旋转，全屏模式也要读取重力传感器来确定往哪个方向横屏。是不是这里出了问题？

我试了一下，打开自动旋转后，把手机横过来就解决了

**Comment by orz12** [comment]
> > 即使关闭系统屏幕旋转，全屏模式也要读取重力传感器来确定往哪个方向横屏。是不是这里出了问题？
> 
> 我试了一下，打开自动旋转后，把手机横过来就解决了

如果是这样的话，就更有可能是原先的实现里面forceSensor引起的问题。我早上已经拜托 @VillagerTom 去修改测试，如果有进展就推到这边来

**Comment by orz12** [comment]
> @orz12 我不是从你的最新版做的更改，没有影响吧？

可能有影响 因为我之前屏蔽了orientationbuilder 起到过效果

**Comment by huajiworld** [comment]
大佬，这个问题还没修好吗

**Comment by orz12** [comment]
> 大佬，这个问题还没修好吗

没办法啊 我复现不出来 不知道问题在哪

**Comment by Lnnznnn** [comment]
12s安卓14hyperos一样，50%几率触发，关闭软件传感器也没用

**Comment by orz12** [comment]
我又改了一下
https://github.com/orz12/pilipala/commit/69d88fbeb1c0bc3330f08e309592d86cda2b5504
不知道能不能解决问题，另外我在播放设置里加了个保底设置，额外横屏，如果还是不行的话，开启该项能否保持住横屏？

**Comment by huajiworld** [comment]
@orz12 https://github.com/orz12/pilipala/assets/65672655/5bbc1d92-8b2c-498a-a01e-5f6666e2e452

变成这样了

**Comment by orz12** [comment]
> @orz12 https://github.com/orz12/pilipala/assets/65672655/5bbc1d92-8b2c-498a-a01e-5f6666e2e452
> 
> 变成这样了

你开了允许屏幕旋转或者额外横屏吗？

**Comment by orz12** [comment]
我可能找到问题了 让我再试一下

**Comment by VillagerTom** [comment]
我这边可以正常横屏了，但是打开系统自动旋转不会自动横屏。

**Comment by VillagerTom** [comment]
关闭[额外横屏]，会先显示竖屏全屏，然后动画过渡到横屏；开启[额外横屏]会直接横屏全屏，没有动画。

**Comment by VillagerTom** [comment]
怪事，又有动画了

**Comment by orz12** [comment]
有新进展了。我给两位群友测试通过，不会再转回来。稍后会编译出v130

**Comment by orz12** [comment]
快来试一下 @huajiworld @kaerwwx

**Comment by huajiworld** [comment]
确实行了，但是退出全屏又不正常了😂退出全屏后还是全屏，只是按钮状态变了

**Comment by orz12** [comment]
> 确实行了，但是退出全屏又不正常了😂退出全屏后还是全屏，只是按钮状态变了

你关掉额外横屏没

**Comment by huajiworld** [comment]
> > 确实行了，但是退出全屏又不正常了😂退出全屏后还是全屏，只是按钮状态变了
> 
> 你关掉额外横屏没

关了

**Comment by orz12** [comment]
早上修了一下

**Comment by huajiworld** [comment]
还是不行呢

**Comment by orz12** [comment]
目前没有遇到其它问题 我暂时关闭了
