### ISSUE TITLE
希望支持动态界面左右滑动，以及支持倍速倍率切换

### ISSUE THREAD

**Issue by warglaive6046** [orz12/pilipala#77]
### 功能描述
动态界面左右滑动以切换到不同关注博主的动态信息；播放设置增加三倍速二倍速的切换选项

### 目标
更方便看到不同博主的内容；自由调节倍速倍率

### 解决方案
不懂前端，只有想法

### 其他
做的很棒，加油

**Comment by warglaive6046** [comment]
F-Droid仓库看到的包，但版本落后了一个小版本，忘提交了，还是国内大学镜像源同步问题？

**Comment by warglaive6046** [comment]
![Screenshot_2024-05-04-11-07-06-677_com looker droidify](https://github.com/orz12/pilipala/assets/92310294/77333609-c5b1-4aac-b742-532d4c31a51c)

**Comment by warglaive6046** [comment]
倍速功能已实现，我之前没找到

**Comment by orz12** [comment]
已支持
