### ISSUE TITLE
取消收藏只能展开后取消再点确认吗

### ISSUE THREAD

**Issue by DrinkingHook** [orz12/pilipala#8]
### 目标
无论开不开启快速收藏，我想取消收藏只能展开收藏后取消掉再点确认，这样感觉有一点麻烦。

开启快速收藏时，第二次单击是取消收藏
不开启就默认收藏到默认收藏夹，二次单击也是取消收藏

### 其他
不知道是不是我操作不对，希望开发大大看一下

**Comment by orz12** [comment]
这个大概可以实现，不过得过一段时间

**Comment by DrinkingHook** [comment]
> 这个大概可以实现，不过得过一段时间

![IMG_20240218_172519.jpg](https://github.com/orz12/pilipala/assets/113015731/8500bfb9-6021-4b55-b6eb-4dfc67c9a5f9)

我测试你最新版的的这个，发现点击收藏或者取消会小概率出现这个，然后这个版本很容易出现卡在一个画面，点什么都不管用，但没有闪退也没提示无响应。我不懂安卓 app 哈，不知道是不是软件的问题，还请见谅。

**Comment by orz12** [comment]
你可以点开 设置 关于 错误日志 看看有没有什么内容复制到这里

**Comment by DrinkingHook** [comment]
> 你可以点开 设置 关于 错误日志 看看有没有什么内容复制到这里 

![Screenshot_2024-02-18-18-11-59-961_com.orz12.PiliPalaX.jpg](https://github.com/orz12/pilipala/assets/113015731/f447bea7-02c6-4ffc-bc5d-4e453e339f8e)

就是没有，有我就粘过来了

**Comment by orz12** [comment]
可能是日志显示不出来 你看下这个显示无数据的界面右上角三个点能不能复制出内容

**Comment by DrinkingHook** [comment]
> 可能是日志显示不出来 你看下这个显示无数据的界面右上角三个点能不能复制出内容

没有内容，这个卡死可能是个别问题，我这会没复现出来

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/bf7667faee5b2829b571c3ff04cecfbf5481bf59
等待编译结束就可以体验了
