### ISSUE TITLE
[bug]打开多个视频，点击🏠返回首页后，后台会继续播放打开的第一个视频

### ISSUE THREAD

**Issue by zbc258** [orz12/pilipala#80]
### 问题描述
开启后台播放，打开多个视频，点击🏠直接返回首页，后台会继续播放打开的第一个视频的音频，但画面已经回到了首页推荐。

### 复现步骤
开启后台播放功能，任意打开多个视频（即打开一个视频，播放一会再从下方推荐栏进入另一个视频）
点击🏠按钮，直接返回首页
此时会发现后台开始播放第一个打开的视频的音频，但画面已经切回首页了。
如果使用返回⬅依次退出打开的所有视频直到回到首页，就不会发生这个问题。
### 预期行为
在用户选择返回首页后，应当马上停止播放后台所有视频和音频

**Comment by zbc258** [comment]
在最新版本该问题依然存在，即使关闭了所有后台播放相关的选项，点击🏠返回首页，后台依然会播放之前打开的第一个视频。

**Comment by orz12** [comment]
这个bug很难定位 我之前也有遇到 但基本触发不了（苦恼

**Comment by orz12** [comment]
感谢你的复现方式 确实更好排查了 近期比较忙 抽空再研究一下

**Comment by zbc258** [comment]
好的，祝工作顺利，希望bug能早日解决。

**Comment by orz12** [comment]
修好了。
