### ISSUE TITLE
[bug]无故弹出”连接错误，请检查网络设置“提示窗口

### ISSUE THREAD

**Issue by zbc258** [orz12/pilipala#81]
### 问题描述
在播放视频时，网络连接正常，视频和评论也能正常加载，但经常无故弹出”连接错误，请检查网络设置“的提示，且无法关闭。

### 预期行为
视频正常播放时不应出现该提示，出现后也应有关闭按钮或一段时间后自动关闭。

**Comment by orz12** [comment]
有些是加载弹幕或者更新观看进度（heartbeat）的时候网络出现问题 但无法关闭是不正常的 一般就显示一两秒 你是否有截图和日志看一下

**Comment by VillagerTom** [comment]
570e4d15ffec6a89bf9cad570a9330494898282e

**Comment by VillagerTom** [comment]
e8ce061c8b8c3ff28e223d4f2e7a6e1dd3956cd8 修复了同时弹出多个toast无法关闭
