### ISSUE TITLE
手动输入accesskey

### ISSUE THREAD

**Issue by Armadilll** [orz12/pilipala#91]
### 功能描述
软件在手表上适配其实非常好没有出现ui的控件重叠等问题,但是登录的界面是白色的加载不出来,请求手动输入accesskey

**Comment by VillagerTom** [comment]
我认为增加扫码等登录比较好

**Comment by orz12** [comment]
access key需要对应的才可以使用 而且门槛比较高
加载不出来是内置webview相关功能都无法使用吗？

**Comment by VillagerTom** [comment]
v1.0.22已增加扫码登录。
